# Generated by Django 6.0 on 2025-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattleapp', '0002_remove_customuser_phone_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('NormalUser', 'NormalUser')], default='NormalUser', max_length=20),
        ),
    ]
