# Generated by Django 6.0 on 2025-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattleapp', '0003_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('history', models.TextField(blank=True, null=True)),
                ('reproduction_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_heat', models.DateField(blank=True, null=True)),
                ('last_ai', models.DateField(blank=True, null=True)),
                ('expected_calving', models.DateField(blank=True, null=True)),
                ('mother_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('father_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('lineage_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
