# Generated by Django 6.0 on 2025-12-08 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattleapp', '0007_rename_assigned_to_task_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('quantity_ltr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattleapp.cow')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_ltr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_ltr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattleapp.milkbuyer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
    ]
