# Generated by Django 6.0 on 2025-12-08 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattleapp', '0008_milkbuyer_milkproduction_milksale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deworming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dewormer_name', models.CharField(max_length=100)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewormings', to='cattleapp.cow')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'Veterinary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('diagnosis_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Recovered', 'Recovered')], default='Ongoing', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='cattleapp.cow')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'Veterinary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'Veterinary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='cattleapp.cow')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='cattleapp.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='cattleapp.cow')),
                ('veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'Veterinary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
    ]
