# Generated by Django 6.0 on 2025-12-08 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattleapp', '0009_deworming_disease_treatment_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('feed_type', models.CharField(choices=[('hay', 'Hay'), ('silage', 'Silage'), ('concentrate', 'Concentrate')], max_length=20)),
                ('quantity_kg', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(help_text='Price per kg')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_cost', models.FloatField(editable=False)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattleapp.feed')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_kg', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_plans', to='cattleapp.cow')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattleapp.feed')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cattleapp.staff')),
            ],
            options={
                'unique_together': {('cow', 'feed', 'date')},
            },
        ),
    ]
